In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("ODI_batting_records_clean.csv")

In [3]:
df

,name,span,matches,innings,not_outs,runs,highest_score,average,balls_faced,strike_rate,century,half_century,ducks,country
0,SR Tendulkar,1990-2012,462.0,451,41,18426,200,44.94,21366,86.23,49,96,19,IND
1,KC Sangakkara,2000-2015,404.0,380,41,14234,169,41.98,18048,78.86,25,93,15,SL
2,V Kohli,2008-2023,292.0,280,44,13848,183,58.67,14797,93.58,50,72,16,IND
3,RT Ponting,1995-2012,375.0,365,39,13704,164,42.03,17046,80.39,30,82,20,AUS
4,ST Jayasuriya,1990-2011,442.0,430,18,13390,189,32.50,14664,91.31,28,68,34,SL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2306,Tanvir Mehdi,1992-1992,1.0,1,0,0,0,0.00,5,0.00,0,0,1,PAK
2307,CK Tshuma,2020-2020,2.0,1,0,0,0,0.00,1,0.00,0,0,1,ZIM
2308,R Walters,2003-2003,2.0,2,0,0,0,0.00,5,0.00,0,0,2,NAM
2309,CM Willoughby,2000-2003,3.0,2,0,0,0,0.00,4,0.00,0,0,2,SA
2310,Zakir Hossain,1998-1998,1.0,1,0,0,0,0.00,1,0.00,0,0,1,BAN

# 1. *Basic Statistics*

In [5]:
#  1. What is the total number of players in the dataset?
print("the total number of players in the dataset is :",df.shape[0])

the total number of players in the dataset is : 2311

In [6]:
df.shape[1]

14

In [7]:
# 2. Which player has played the most matches?
most_matches_player=df[['matches','name']].sort_values(by='matches',ascending=False).head(1)

In [8]:
most_matches_player

   matches          name
0    462.0  SR Tendulkar

In [9]:
player_name=most_matches_player['name'].iloc[0] #access through the indes[0]

In [10]:
print("The most matches player name is : ",player_name)

The most matches player name is :  SR Tendulkar

In [11]:
# 3. Which player has the highest number of runs scored?
highest_runs_player=df[['runs','name']].sort_values(by='runs',ascending=False).head(1)

In [12]:
print("Highest runs player name is :", highest_runs_player['name'].loc[0])
print("Highest runs :", highest_runs_player['runs'].loc[0])

Highest runs player name is : SR Tendulkar
Highest runs : 18426

In [13]:
# 4. What is the average number of matches played by the players?
print("Average numbers of matches:",df['matches'].mean())

Average numbers of matches: 39.33189095629598

In [14]:
# 5. How many players have a batting average above 50?
players_above_50_avg=df[df['average']> 50 ].shape[0]  #shape[0]=count the total number of rows
print("players_above_50_avg :",players_above_50_avg)

players_above_50_avg : 37

# 2. *Top Performers*

In [16]:
#  6. Who has the highest batting average in the dataset?
highest_batting_avg_player=df[['average','name']].sort_values(by='average',ascending=False).head(1)

In [17]:
print("Highest Batting average player name i s:",highest_batting_avg_player['name'].loc[1282])
print("Highest average is :",highest_batting_avg_player['average'].loc[1282])

Highest Batting average player name i s: AL Kandappah
Highest average is : 97.0

In [18]:
#  7. Who has scored the highest individual score in an innings?
highest_score_player=df[['highest_score','name']].sort_values(by='highest_score',ascending=False).head(1)

In [19]:
print(" the highest individual score in an innings player name is :",highest_score_player['name'].loc[11])
print(" the highest individual score in an innings :",highest_score_player['highest_score'].loc[11])

 the highest individual score in an innings player name is : RG Sharma
 the highest individual score in an innings : 264

In [20]:
# 8. How many players have scored more than 10,000 runs?
print("Total number of players scored more than 10,000 runs :",df[df['runs']>10000].shape[0])

Total number of players scored more than 10,000 runs : 15

In [21]:
#  9. Which player has the most centuries?
most_centuries_player=df[['century','name']].sort_values(by='century',ascending=False).head(1)

In [22]:
print(most_centuries_player['name'].loc[2],"has the most centuries")
print("Total centuries are :",most_centuries_player['century'].loc[2])

V Kohli has the most centuries
Total centuries are : 50

In [23]:
# 10. Which player has the most half-centuries?
most_half_centuries_player=df[['half_century','name']].sort_values(by='half_century',ascending=False).head(1)

In [24]:
print(most_half_centuries_player['name'].loc[0],"has the most half centuries")
print("Total half centuries are :",most_half_centuries_player['half_century'].loc[0])

SR Tendulkar has the most half centuries
Total half centuries are : 96

# 3. *Country-wise Analysis*

In [26]:
#11. Which country has the most players in the dataset?
x1=df.groupby("country")

In [27]:
x2=x1['name'].count()

In [28]:
most_player_in_a_dataset=x2.sort_values(ascending=False)

In [29]:
most_player_in_a_dataset

country
IND      181
WI       178
PAK      174
ENG      172
SL       160
NZ       153
AUS      147
ZIM      140
SA       134
BAN      129
UAE      100
CAN       82
SCOT      79
NED       78
IRE       61
AFG       53
KENYA     47
NAM       39
USA       38
HKG       36
NEP       33
BER       33
PNG       26
OMA       24
JER       14
Name: name, dtype: int64

In [30]:
print(most_player_in_a_dataset.idxmax()," has the most players in the dataset")

IND  has the most players in the dataset

In [31]:
print(most_player_in_a_dataset.max(),"number of players in data set")

181 number of players in data set

In [32]:
#11. Which country has the most players in the dataset?
players_per_country=df['country'].value_counts()

In [33]:
print(players_per_country.idxmax(), "has the most players in the dataset")

IND has the most players in the dataset

In [34]:
print(players_per_country.max(),"number of players in data set")

181 number of players in data set

In [35]:
#12. Who is the highest run-scorer for India?
Indian_Player=df[df['country']=='IND']

In [36]:
highest_Indian_run_scorer=Indian_Player[['runs','name']].sort_values(by='runs',ascending=False).head(1)

In [37]:
print(highest_Indian_run_scorer['name'].loc[0],"is the highest run-scorer for India")
print(highest_Indian_run_scorer['runs'].loc[0],"is the highest runs for India")

SR Tendulkar is the highest run-scorer for India
18426 is the highest runs for India

In [38]:
# 13. What is the average strike rate of Australian players?
Australian_Player=df[df['country']=='AUS']

In [39]:
print(Australian_Player['strike_rate'].mean(),"is the average strike rate of Australian players",)

75.21278911564626 is the average strike rate of Australian players

In [40]:
#14.How many players from Sri Lanka have scored more than 5,000 runs?
Srilankan_Player=df[df['country']=='SL' ]

In [41]:
print(Srilankan_Player[Srilankan_Player['runs'] > 5000].shape[0]," players from Sri Lanka have scored more than 5,000 runs")

9  players from Sri Lanka have scored more than 5,000 runs

In [42]:
# 15. Which country's players have the highest average batting average?
average_batting_avg_by_country=df.groupby('country')['average'].mean()

In [43]:
print(average_batting_avg_by_country.idxmax(),"country's players have the highest average batting average")
print(average_batting_avg_by_country.max()," is the highest average batting average of South Africa")

SA country's players have the highest average batting average
21.58044776119403  is the highest average batting average of South Africa

In [44]:
# Split the 'span' column into 'start_year' and 'end_year'
df[['start_year', 'end_year']] = df['span'].str.split('-', expand=True)

# Convert 'start_year' and 'end_year' to numeric (integer) types
df['start_year'] = pd.to_numeric(df['start_year'])
df['end_year'] = pd.to_numeric(df['end_year'])

# Display the first few rows to check
df.head()

,name,span,matches,innings,not_outs,runs,highest_score,average,balls_faced,strike_rate,century,half_century,ducks,country,start_year,end_year
0,SR Tendulkar,1990-2012,462.0,451,41,18426,200,44.94,21366,86.23,49,96,19,IND,1990,2012
1,KC Sangakkara,2000-2015,404.0,380,41,14234,169,41.98,18048,78.86,25,93,15,SL,2000,2015
2,V Kohli,2008-2023,292.0,280,44,13848,183,58.67,14797,93.58,50,72,16,IND,2008,2023
3,RT Ponting,1995-2012,375.0,365,39,13704,164,42.03,17046,80.39,30,82,20,AUS,1995,2012
4,ST Jayasuriya,1990-2011,442.0,430,18,13390,189,32.50,14664,91.31,28,68,34,SL,1990,2011

In [45]:
#16. What is the average number of runs scored per match for players active between 2000 and 2010?
players_2000_2010=df[(df['start_year']>=2000) & (df['end_year'] <=2010)]

In [46]:
runs_per_match=players_2000_2010['runs']/players_2000_2010['matches']

In [47]:
average_runs_per_match=runs_per_match.mean()

In [48]:
print(average_runs_per_match, "is the average number of runs scored per match for players active between 2000 and 2010")

10.758579000941257 is the average number of runs scored per match for players active between 2000 and 2010

In [49]:
# 17. How has the strike rate of players evolved over different decades (1990s, 2000s, 2010s)?
def classify_decade(year):
    if 1990 <= year < 2000:
        return '1990s'
    elif 2000 <= year < 2010:
        return '2000s'
    elif 2010 <= year < 2020:
        return '2010s'
    else:
        return 'Other'
df['decade'] = df['start_year'].apply(classify_decade)

In [50]:
# Calculate the average strike rate for each decade
average_strike_rate_by_decade = df.groupby('decade')['strike_rate'].mean()
print(average_strike_rate_by_decade)

decade
1990s    62.105370
2000s    64.402608
2010s    71.175719
Other    71.880592
Name: strike_rate, dtype: float64

In [51]:
#18. Compare the average runs scored by players who started their careers in the 1990s versus those who started in the 2000
players_runs_1990s=df[(df['start_year'] >=1990) & (df['start_year'] < 2000)]
players_runs_2000s=df[(df['start_year'] >=2000) & (df['start_year'] < 2010)]

In [52]:
avg_runs_1990s=players_runs_1990s['runs'].mean()
avg_runs_2000s=players_runs_2000s['runs'].mean()

In [53]:
print("Average runs scored by players who started in the 1990s:",avg_runs_1990s)
print("Average runs scored by players who started in the 2000s:",avg_runs_2000s)

Average runs scored by players who started in the 1990s: 1064.932283464567
Average runs scored by players who started in the 2000s: 828.7291066282421

In [54]:
# 19. How many players have maintained a batting average above 40 throughout their careers?
average_40s_above=df[df['average']>40]

In [55]:
print(average_40s_above.shape[0],": players have maintained a batting average above 40 throughout their careers")

134 : players have maintained a batting average above 40 throughout their careers

In [56]:
#20. Who has the highest runs per innings ratio?
df['runs_per_innings']=df['runs']/df['innings']

In [57]:
highest_rpi_player = df[['name', 'runs_per_innings']].sort_values(by='runs_per_innings', ascending=False).head(1)

In [58]:
print(highest_rpi_player['name'].iloc[0],"has the highest runs per innings ratio")

CRM Douglas has the highest runs per innings ratio

In [59]:
# 21. What is the correlation between the number of matches played and total runs scored?
correlation = df['matches'].corr(df['runs'])

In [60]:
print(f"Correlation between matches played and runs scored:" ,correlation)

Correlation between matches played and runs scored: 0.8610994217985447

In [61]:
#22. Which player has the highest runs per match ratio?

df['runs_per_matches']=df['runs']/df['matches']

In [62]:
highest_rpm_player = df[['name', 'runs_per_matches']].sort_values(by='runs_per_matches', ascending=False).head(1)

In [63]:
print(highest_rpm_player['name'].loc[1200],"has the highest runs per match ratio")

CRM Douglas has the highest runs per match ratio

In [64]:
# 23. What is the average number of balls faced per innings for players with a strike rate above 90?
high_strike_rate_players = df[df['strike_rate'] > 90]

In [65]:
high_strike_rate_players['balls_per_innings'] = high_strike_rate_players['balls_faced'] / high_strike_rate_players['innings']

C:\Users\arindam444\AppData\Local\Temp\ipykernel_10844\524089869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  high_strike_rate_players['balls_per_innings'] = high_strike_rate_players['balls_faced'] / high_strike_rate_players['innings']

In [66]:
average_balls_per_innings = high_strike_rate_players['balls_per_innings'].mean()

In [67]:
print("Average number of balls faced per innings for players with a strike rate above 90: ",average_balls_per_innings)

Average number of balls faced per innings for players with a strike rate above 90:  19.265437362390262

In [68]:
# 24. How many players have scored more than 15 centuries but less than 30 half-centuries?
good_player=df[(df['century']>15) & (df['half_century']<30)]

In [69]:
print(good_player.shape[0],"players have scored more than 15 centuries but less than 30 half-centuries")

1 players have scored more than 15 centuries but less than 30 half-centuries

In [70]:
#25.Identify players who have more ducks than centuries.
more_ducks_player=df[df['ducks']>df['century']]

In [71]:
player_names=more_ducks_player['name']

In [72]:
print("Players who have more ducks than centuries:")
for i in player_names:
    print(i)

Players who have more ducks than centuries:
ST Jayasuriya
DPMD Jayawardene
Inzamam-ul-Haq
R Dravid
AC Gilchrist
Yuvraj Singh
MS Atapattu
Tamim Iqbal
HH Gibbs
Shahid Afridi
SP Fleming
MJ Clarke
Mushfiqur Rahim
EJG Morgan
Shakib Al Hasan
Shoaib Malik
PA de Silva
Younis Khan
M Azharuddin
NJ Astle
WU Tharanga
A Flower
BRM Taylor
Mohammad Hafeez
GW Flower
BB McCullum
JN Rhodes
AD Mathews
RR Sarwan
SR Waugh
SR Watson
H Masakadza
SK Raina
MN Samuels
A Ranatunga
WJ Cronje
Ijaz Ahmed
IR Bell
Mahmudullah
A Jadeja
DR Martyn
ADR Campbell
Misbah-ul-Haq
JP Duminy
PD Collingwood
A Symonds
Abdul Razzaq
JC Buttler
CL Cairns
Aamer Sohail
CD McMillan
MV Boucher
AJ Stewart
SB Styris
DA Miller
CZ Harris
Saleem Malik
WTS Porterfield
E Chigumbura
ME Trescothick
AJ Strauss
RS Mahanama
TWM Latham
RP Arnold
GJ Maxwell
DJ Cullinan
BKG Mendis
LD Chandimal
GA Hick
RS Kaluwitharana
NV Knight
KJ O'Brien
L Klusener
HP Tillakaratne
SM Pollock
Mohammad Ashraful
MA Taylor
BA Stokes
Mohammad Nabi
SO Tikolo
A Flintoff
T Taibu
CR Ervine
AC Parore
NS Sidhu
Moin Khan
MDKJ Perera
Kamran Akmal
Wasim Akram
AN Cook
HDRL Thirimanne
Umar Akmal
KJ Coetzer
DM Bravo
Ramiz Raja
V Sibanda
DJ Bravo
RD Berrington
AM Rahane
AP Gurusinha
HH Streak
PV Simmons
WW Hinds
IJL Trott
RA Jadeja
M Kaif
SV Carlisle
Salman Butt
RG Twose
KA Pollard
GJ Whittall
RS Bopara
MR Marsh
Ahmed Shehzad
NJ O'Brien
Litton Das
AC Hudson
VG Kambli
CJ Chibhabha
JDP Oram
Asghar Afghan
TM Odoyo
L Vincent
GP Thorpe
MM Ali
KR Rutherford
NLTC Perera
N Hussain
RR Singh
DL Haynes
SL Campbell
DL Vettori
JO Holder
Hashmatullah Shahidi
S Matsikenyeri
JC Adams
Shahriar Nafees
D Ramdin
Habibul Bashar
AK Markram
RL Powell
CL White
GC Wilson
Najibullah Zadran
HM Nicholls
CO Obuya
Javed Miandad
WPUJC Vaas
KO Otieno
Soumya Sarkar
A Vala
MH Cross
MP Vaughan
GD Elliott
LMP Simmons
Aftab Ahmed
Imran Nazir
SV Manjrekar
DJG Sammy
MS Wade
DM de Silva
RD Jacobs
NH Fairbrother
OA Shah
Khaled Mashud
AT Carey
Samiullah Shinwari
DJ Hussey
MA Atherton
Mashrafe Mortaza
MJ Greatbatch
V Aravind
HH Pandya
KD Karthik
HG Munsey
Imran Farhat
CB Wishart
Rashid Latif
DA Gunawardene
MG Erasmus
KLT Arthurton
BA Young
IA Healy
AR Border
UDU Chandana
CK Kapugedera
LPC Silva
RK Paudel
SC Williams
M Prabhakar
DR Smith
AH Jones
IK Pathan
J Charles
CR Woakes
Azhar Mahmood
RS Morton
SA Edwards
JM Kemp
RD Shah
Rohan Mustafa
MA Ouma
JDS Neesham
MP Stoinis
Aaron Jones
HJH Marshall
MD Patel
DD Ebrahim
Nasir Jamshed
MO Odumbe
P Utseya
MP O'Dowd
Aasif Sheikh
L Ronchi
Najmul Hossain Shanto
TP Ura
JD Ryder
DO Obuya
MJ Santner
Anamul Haque
GH Dockrell
Asad Shafiq
PG Fulton
Sabbir Rahman
Mehidy Hasan Miraz
KMDN Kulasekara
JR Hopes
SM Katich
FDM Karunaratne
Rashid Khan
Javed Omar
MA Leask
Raqibul Hasan
AA Obanda
MS Sinclair
MD Shanaka
GA Gooch
Muhammad Waseem
MJ Prior
Nasir Hossain
W Barresi
NR Mongia
C Munro
JEC Franklin
AB Agarkar
Basit Ali
MN Waller
RR Rossouw
Harbhajan Singh
SG Law
Alok Kapali
Gulbadin Naib
D Mongia
HDPK Dharmasena
K Bhurtel
Shaiman Anwar
Noor Ali Zadran
WIA Fernando
Junaid Siddique
SR Taylor
Mohammad Rafique
RW Chakabva
B Lee
S Samarawickrama
TM Moody
Nawroz Mangal
DL Houghton
T Mishra
MF Maharoof
CJ Anderson
HS Modi
ES Szwarczynski
B Zuiderent
PA Strang
S Bau
F Behardien
NL McCullum
DS Smith
JK Kamande
C Kieswetter
BA King
Javed Ahmadi
KD Mills
JM How
AD Russell
JP Faulkner
AG Prince
SK Warne
Muhammad Usman
KOA Powell
Rajin Saleh
PW Borren
NFI McCallum
Ayaan Khan
Khaled Mahmud
Asif Mujtaba
MJ Slater
Imad Wasim
MJ Horne
R Powell
BFW de Leede
Naeem Islam
DF Watts
Fawad Alam
Aarif Sheikh
SA Thomson
JF Mooney
Waqar Younis
RR Watson
SF Mire
MG Johnson
Imran Khan
CP Rizwan
Akram Khan
Chirag Suri
NT Broom
RP Burl
A Kumble
CM Spearman
RV Uthappa
L Siaka
RR Hendricks
AN Kervezee
S Dhaniram
AJ Hall
DS Airee
PW Hasaranga
JWA Taylor
J Srinath
Basil Hameed
G Malla
TT Bresnan
SHT Kandamby
DJ Richardson
MA Vermeulen
RR Pant
GO Jones
TT Samaraweera
Shadab Khan
AL Phehlukwayo
Towhid Hridoy
RS Kalpage
D Ganga
CA Ingram
N Kapil Dev
SSJ Brooks
BM McMillan
LJ Tucker
N Vanua
CK Coventry
SJ Modani
PJ Moor
AR McBrine
AU Rashid
Sharjeel Khan
YK Pathan
JN Loftie-Eaton
JM Davison
Z Khan
GB Hogg
Babar Hayat
RL Chase
IH Romaine
JA Morkel
Sohaib Maqsood
Abdur Razzak
AR White
SA Yadav
CN Evans
Rizwan Cheema
Aminul Islam
CA Soper
AR Cusack
AG Cremer
DT Johnston
C de Grandhomme
AM Samad
TG Southee
Wahab Riaz
PA Patel
CJ Nevin
K Doriga
JJ Smit
Shoaib Khan
MA Ealham
IJ Harvey
Mohammad Mithun
Saqlain Mushtaq
JG Wright
R Ashwin
LJ Wright
W Madhevere
Mohammad Nadeem
J Mubarak
PA Wallace
SM Ervine
PL Symcox
AC Waller
AT Nidamanuru
JR Murray
M Muralidaran
DA Marillier
B Sharki
UC Hathurusingha
AC Botha
DJ Willey
KR Mayers
LE Plunkett
S Ramesh
DL Hemp
BMAJ Mendis
Mosaddek Hossain
DLS van Bunge
PSP Handscomb
JN Mohammed
GR Larsen
AM Blignaut
Khawar Ali
DJ Nash
RR Patel
R Mutumbami
GJ Rennie
J Botha
D Gough
AJ Hollioake
K Srikkanth
Afif Hossain
RIC Holder
AL Logie
XM Marshall
Sompal Kami
Simi Singh
LOB Cann
SB Joshi
RT Latham
FH Allen
JL Carter
Sandeep Goud
KU Carty
BJ Hodge
WD Parnell
Tushar Imran
CD Wallace
BJ Watling
MA Starc
C White
SL Malinga
RM Haq
MK Pandey
CR Brathwaite
LS Livingstone
Mominul Haque
RJ Peterson
B Kumar
MRJ Watt
GS Blewett
TJ Friend
T Duffin
Aayan Afzal Khan
Mohammad Wasim
SM Sharif
SCJ Broad
NN Odhiambo
SJ Myburgh
Naved-ul-Hasan
LK Germon
Mudassar Bukhari
TAM Siriwardana
CEL Ambrose
SP O'Donnell
KM Dabengwa
PK Amre
Dawlat Zadran
JN Frylinck
DP Viljoen
AO Suji
PR Reiffel
AR Nurse
Ghulam Shabber
GP Swann
JH Davey
NK Patel
JJ Tucker
MAR Samarasekera
DJ Callaghan
PJ Cummins
AR Patel
Naimur Rahman
JWM Dalrymple
AC Cummins
R McLaren
CS Baugh
AA Mulla
SR Patel
DJ Reekers
TN de Grooth
DA Minors
BG Rogers
S Lee
LV van Beek
Karim Sadiq
AJ Bichel
SM Curran
H Patel
Athar Ali Khan
Umar Gul
GEF Barnett
R Gunasekera
GS Ballance
MD Dai
H Hiri
WV Raman
Mehrab Hossain
RA Harper
JP Maher
Usman Ghani
DN Chudasama
IDS Smith
CJO Smith
LM Jongwe
Shafiqullah
JS Malhotra
CN Ackermann
AS Joseph
MN van Wyk
M Jansen
AS Hansra
S Prasanna
AR Adams
SR Waters
CO Browne
Farhad Reza
Karan KC
JP Inglis
Suraj Kumar
Ahmed Raza
GB Brent
HC Brook
RW Price
ID Blackwell
F Mutizwa
MR Adair
TBM de Leede
WS Jayantha
Sohail Tanvir
R Shepherd
Mohammad Naveed
BM Duckett
Naseem Khushi
R Trumpelmann
AB Barath
Shoaib Akhtar
DN Patel
T Thushara
PJ Ongondo
Aryan Lakra
Mirwais Ashraf
Mushtaq Ahmed
CM McBride
AF Giles
IT Botham
EA Brandes
Hannan Sarkar
Hasan Ali
SR Mukkamalla
U Bhatti
S Lamichhane
Al Sahariar
CC Lewis
S Chattergoon
PJ Forrest
IG Holland
DW Steyn
Minhajul Abedin
DT Tiripano
Mohammad Amir
SP Narine
PAJ DeFreitas
SS Karim
Mohammad Saifuddin
R Rampaul
Shahriar Hossain
Hazratullah Zazai
WK McCallan
RC Irani
Mushfiqur Rahman
BJ Patel
K Rabada
NP Kenjige
IR Bishop
AD Brown
ADS Fletcher
J Gumbie
Nasir Jamal
Wajahatullah Wasti
SJ Baard
R Hekure
PM Seelaar
RDB Croft
Ashfaq Ahmed
GP Wickramasinghe
DNT Zoysa
HH Kanitkar
CN Greaves
SD Outerbridge
Tapash Baisya
KA Edwards
Manjural Islam Rana
S Mukuddem
AH Omarshah
D Wiese
D Khanal
SN Thakur
ZE Surkari
MH Yardy
ML Nkala
Saeed Ajmal
AC Agar
RP Snell
KMA Paul
DR Brown
HP Rinke
Faisal Iqbal
NAM McLean
Mohammad Sami
D la Cock
VV Morea
BR Hartland
N Chopra
BC Hollioake
Nafees Iqbal
TK Musakanda
KAJ Roach
Ihsanullah
DM Benkenstein
TK Curran
LE Bosman
CMW Read
SA Abbott
PA Nixon
Zahoor Elahi
DN Crookes
DR Tuffey
A Zampa
SE Bond
P Kumar
Tanwir Afzal
A Dananjaya
RN Lewis
Sanuar Hossain
SMSM Senanayake
JN Gillespie
IDR Bradshaw
LG Howell
JAR Blain
NO Miller
LP van Troost
Kashif Daud
S Randiv
JE Taylor
AV Vadher
Mehrab Hossain jnr
JM Anderson
JW Hastings
Jahurul Islam
W Larkins
M Morkel
G Toka
RJ Ratnayake
PVD Chameera
AJ Hosein
Shamsur Rahman
Aaqib Javed
Afsar Zazai
S Jyoti
M Theekshana
SP Patil
Tanzid Hasan
HN Ya France
HJW Gardiner
Aizaz Khan
K Birkenstock
ML Udawatte
SS Dighe
MJ Henry
AD Poynter
SA Wijeyeratne
NM Coulter-Nile
J Edness
KS More
HA Varaiya
JAH Marshall
AR Caddick
DE Budge
MA Suji
AD Mascarenhas
SM Davies
RAS Lakmal
Qaiser Ali
Hasan Raza
Musa Ahmed
GD Drummond
CM Wright
Amjad Javed
CRD Fernando
T Panyangara
KA Maharaj
DC Thomas
NS Poonia
I Udana
Enamul Haque
GJ Hopkins
Khurram Manzoor
Mujeeb Ur Rahman
GR Codrington
JP Crawley
GJ Delany
Iftikhar Anjum
C Madande
STR Binny
TM Dowlin
DR Flynn
AY Karim
M Dillon
Raza-ur-Rehman
Faheem Ashraf
BP Julian
DN Wellalage
KM Jarvis
DAJ Bracewell
BKV Prasad
HS Baidwan
BJ McCarthy
Mohammed Shami
Jasdeep Singh
DR Lockhart
Y Venugopal Rao
NR Kumar
FA Rose
EO Simons
Taskin Ahmed
TA Boult
V Dahiya
PL Taylor
PJL Dujon
NO Perry
FRJ Coleman
DJM Short
K Gore
KS Lokuarachchi
S Fouche
WP Masakadza
TL Chatara
D Bau
DL Chahar
JA Rennie
IS Sodhi
FA Allen
NW Bracken
Z Crawley
M Ntini
GA Lamb
MR Swart
TE Blain
T Maruma
BM Scholtz
Shaheen Shah Afridi
A Sharafu
AP Devcich
GSNFG Jayasuriya
ASA Perera
Saqib Zulfiqar
C Pringle
MM Iqbal
D Pretorius
CJ Smith
CA Walsh
TN Madondo
Shabir Noori
Kuldeep Yadav
CJ McKay
Mohammad Shahzad
Usman Limbada
JA McCollum
BAW Mendis
TJ Murtagh
BN Cooper
T Mupariwa
SW Poynter
CJ Jordan
JL Ontong
MD Marshall
SJ Benn
A Dutt
SB Bangar
WKM Benjamin
DG Cork
AF Milne
WF Stelling
N Davin
TC Bastiampillai
A Saud
SB Doull
Hasibul Hossain
PS de Villiers
SW Masakadza
J Smits
R Ngarava
CPH Ramanayake
AR Whittall
RE van der Merwe
A McGrath
DES Maxwell
Khurram Chohan
D Bishoo
KP Meiyappan
Shan Masood
JC Tredwell
MV Nagamootoo
CD Cumming
SC Joseph
E Schiferli
HMCM Bandara
Mustafizur Rahman
J Kila
JJ Martin
Imran Tahir
T Kaitano
T Marumani
MA Wood
MP Maynard
DK Morrison
AM Ellis
RML Taylor
C Zhuwao
Akram Raza
DW Fleming
Zahoor Khan
VD Philander
RG Aga
AR Khurasiya
BOP Fernando
Khalid Latif
GM Strydom
JA Burns
TS Chisoro
R Clarke
LN Onyango
Rubel Hossain
Shoaib Mohammad
Abdur Rehman
EH Hutchinson
D Langford-Smith
MB Loye
DE Bernard
ARC Fraser
OD Gibson
CR Matthews
A Nehra
CAH Stevenson
D Williams
AF Buurman
HMRKB Herath
MV Fleming
JW Jenner
SN Netravalkar
ST Finn
KD Shah
A Sharma
R Vijay Bharadwaj
Krishna Chandran
Shafiul Islam
Arshad Khan
RJ Sidebottom
RK Chauhan
Fayyaz Butt
D Keulder
Bazid Khan
TS Kamunhukamwe
MSK Prasad
RJ Trott
KTGD Prasad
D Ravu
DT Hondo
A Nel
Yasir Shah
Dhiman Ghosh
N Dutta
M Kartik
A Nao
CP Senanayake
JR Hazlewood
PA Jaques
Kaleemullah
CA Young
A Maregwede
M van Jaarsveld
LR Williams
Ziaur Rahman
LH Ferguson
B Muzarabani
B Evans
SK Gupta
L Balaji
DBL Powell
AK Sharma
V Yadav
DH Brain
NB Mahwire
CAK Rajitha
Hamza Tariq
GF Labrooy
GD McGrath
MO Jones
DL Maddy
Haseeb Amjad
DP Hyatt
RDM Leverock
JDF Vandersay
Taijul Islam
CJ McDermott
SS McKechnie
Hamid Hassan
KO Meth
RK Kleinveldt
CD Collymore
RP Singh
Junaid Siddique
MW Priest
JW Wilson
Ehsan Khan
Waqas Barkat
Yasir Ali
Arshad Laeeq
XJ Doherty
WR James
S Elworthy
AC Evans
WB Rankin
Irfan Ahmed
Saad Nasim
DCC Borden
LR Johnson
I Maraj
GM Ewing
SP Khakurel
PA van Meekeren
M Levitt
AA Donald
Mohammad Naim
HK Olonga
JS Patel
KL Tucker
VC Drakes
Kabir Ali
MR Gillespie
BC Strang
JJ Bumrah
SJ Harmison
L Ngidi
SG Peall
DB Vengsarkar
GB Murgatroyd
Bilawal Bhatti
PBB Rajapaksa
JJ van der Wath
SS Cottrell
B Mavuta
AD Mullally
R Vinay Kumar
BV Vitori
NE Bonner
PJC Hoffmann
KAD Hurdle
SI Mahmood
IG Butler
GI Maiden
AG Davies
LHD Dilhara
Shoriful Islam
LJ Koen
PWA Mulder
AM Phangiso
GA Rogers
Shahid Wasif
S Sriram
Syed Rasel
Jai P Yadav
Aftab Alam
G Goudie
TR Gripper
JB Little
Mohammad Wasim (1)
Shahadat Hossain
UT Yadav
AC Dale
YS Chahal
NM Lyon
KJ Abbott
TL Best
CA Lynn
KW Richardson
MS Kasprowicz
MM Patel
FH Edwards
CK Langeveldt
KV Morea
R Telemachus
Waheed Ahmed
BA Murphy
OL Pitcher
P Sarraf
I Sharma
KED Carroll
G Motie
Sharafuddin Ashraf
SR Clark
Haris Rauf
Junaid Khan
FJ Klaassen
SO Ngoche
C Overton
M Sheikh
SJ Cook
Junaid Siddiqui
N Madziva
HJC Mol
Nadeem Ahmed
Shapoor Zadran
PR Adams
KCG Benjamin
RD King
RG Petrie
H Osinde
PADLR Sandakan
AAP Atkinson
MG Hughes
N Pokana
CE Cuffy
JB Reva
Azhar Saeed
Dolar Mahmud
MN Hart
CBRLS Kumara
GC Small
RM West
GE Bradburn
JJ Celestine
NC McGarrell
MBS Jonkman
EAR de Silva
Imran Haider
TMK Mawoyo
G Coetzee
Ehsanul Haque
CB Mpofu
M Shumba
LL Tsotsobe
MW Douglas
EC Rainsford
Arshad Ali
RWT Key
Mohammad Iqbal
Manjural Islam
Mohammad Sharif
RAP Nissanka
CAK Walton
JE Brinkley
TK Canning
D Dasgupta
CA Pujara
RA Reifer
DE Bollinger
NE Clarke
AJ Pycroft
J Theron
CT Tremlett
Hasan Mahmud
CK Hooper
E Otieno
D Ranatunga
Arafat Sunny
Mohammad Irfan
MW Pringle
PC Strydom
Zafar Iqbal
A Codrington
Mohammad Hasnain
MW Gatting
Mohammed Siraj
J Nyumbu
Skhawat Ali
S Thuraisingam
NA de Groot
RD McCann
S Sreesanth
JH Stander
JG Bracewell
HR Bryan
Faisal Hossain
AR Kapoor
R Klein
A Mishra
VM Nyauchi
Salman Faris
Fareed Ahmad
MH Richardson
PA Hitchcock
Bilal Asif
PC Connell
AIC Dodemaide
Kaleem Sana
Khaliq Dad
A Nortje
ML Patel
Usama Mir
BTJ Wheal
GA Briant
KSC de Silva
MW Forde
MADI Hemantha
GD Lloyd
AA Paradkar
JT Ball
PP Chawla
CKB Kulasekara
N M'shangwe
Najeeb Amar
GH O'Brien
T Shamsi
KAR Hodge
T Lungameni
Naveen-ul-Haq
LN Rajbanshi
PW Gunaratne
D Madushanka
G Mylvaganam
KR Pushpakumara
JO Troughton
PKD Chase
N Pradeep
Nazmul Hossain
JO Ngoche
KT Sandher
RJW Topley
SD Udal
SM Warnapura
Ata-ur-Rehman
N Dhamba
RMS Eranga
AS Luseno
M Mbangwa
Mohammad Asif
T Gibbons
PARP Perera
S Snater
AS Wassan
W Watson
JC Archer
SLV Raju
SP Terry
Amir Hayat
JD Nel
Noor Ahmad
MM Sharma
PM Siddle
GJ Batty
Bilal Khan
M Cheruparambil
PT Collins
Ehsan Nawaz
MVT Fernando
AJ Ireland
Mohammad Haris
TCB Fernando
DI Joyce
Adeel Raja
J Jarvis
DS Mohanty
Usman Rafiq
MR Whitney
KS Airee
SA Ankola
HAPW Jayawardene
TP Kamungozi
BL Kotze
Rumman Raees
T Suri
BA Williams
Hamza Tahir
PW Jarvis
A Kuruvilla
TG Shaw
Tareq Aziz
RJ van Vuuren
Sultan Zarawani
RJ Blakey
Naved Anjum
SW Tait
ST Gabriel
MJ Mason
SB O'Connor
Amir Hamza
JO Angara
HAG Anthony
SJ Massiah
CP Tremain
Afzaal Haider
DW Headley
Kamran Shazad
Mohammad Salman
BP Patterson
Shafiuddin Ahmed
O Thomas
JP Behrendorff
AB Dinda
Fazalhaq Farooqi
EE Hemmings
I Wardlaw
Ali Khan
AP Igglesden
MR Johnson
SI Kamea
IL Philip
ADJ Pitcher
AF Sattaur
JW Dernbach
MC Snedden
AG Wharf
F Kasteni
SSB Magala
HB Shipley
GI Allott
MJ Hoggard
JNT Seales
KCB Jeremy
CEW Silverwood
N Ifill
RL Johnson
BP Loots
FN Otieno
RS Higgins
A van der Merwe
Asghar Ali
Asif Mahmood
IPP Batuwitarachchi
VJ Kingma
LD Madushanka
Mohammad Akram
Muhammad Jawadullah
IA Nicolson
D Soraine
LS Baker
HT Davis
RO Hurley
SP Krishnamurthi
AMN Munasinghe
B Regmi
Asim Saeed
Danish Kaneria
RP de Groen
Enamul Haque jnr
M Hayward
AJ McKay
PJK Mooney
T Muzarabani
Naeemuddin Aslam
TS Nethula
Noor-ul-Haq
LJ Burger
NGRP Jayasuriya
NM Kulkarni
MG Neser
M Pathirana
TR Ambrose
MA Aponso
HK Bennett
JSE Dunford
JJ Esmeijer
JOA Gordon
W Jaffer
BMW Patterson
SM Boland
Fahad Usman
AG Huckle
DE Malcolm
KIW Wijegunawardene
Yamin Ahmadzai
VR Aaron
BS Browne
PA Desai
J Kariko
CS Martin
EZ Matambanadzo
PDRL Perera
CG Rackemann
Rahat Ali
SS Raul
RL Sanghvi
DG Blampied
WCA Ganegama
Izatullah Dawlatzai
EA Moseley
CS Pandit
NA Statham
RF van Oosterom
GD Campbell
MT Chinouya
Fahim Muntasir
AP Grayson
Harvinder Singh
TJG Pringle
DB Rundle
Usman Shinwari
TM Alderman
ND Hirwani
G Snyman
Talha Jubair
RK Whelan
Al-Amin Hossain
MI Black
Jahangir Alam
Jay Odedra
GK Pandey
LN Roche
AM Salvi
BB Seebaran
B Stanlake
RW Staple
SL Watkin
P Wilson
M Zondeki
Basir Ahamad
NR Dyer
Ebadot Hossain
CK Kruger
MJ Petrie
DOD Rikhi
CJPG van Zyl
Anisur Rahman
Elias Sunny
Fahad Nawaz
PG Gillespie
KC Hodsoll
Junaid Zia
EJB Miles
Nurul Abedin
M Prasidh Krishna
GJ Thompson
Umran Malik
JA Duffy
AM Fernando
S Kaul
JM Mennie
Mohammad Kashif
Moniruzzaman
W Mwayenga
KA Patel
K Phillip
LC Romero
BA Westdijk
Aman Ali
J Angel
MRCN Bandaratilleke
JE Benjamin
D Birrell
TJ Bishop
DL Blake
NM Carter
K Christie
JI de Villiers
Fahad Alhashmi
Fazle Mahmud
R Flannigan
D Foxcroft
VD Grandia
RG Hart
SM Harwood
RC Haynes
PHT Kaushal
GJP Kruger
Mohammad Talha
Najaf Shah
Nasir Hameed
MB Owens
NT Pascal
AG Puttick
Rafiqul Islam
DR Ramsammy
N Ranatunga
Raza Hasan
Rizwan Latif
Shahbaz Ahmed
T Sangha
Shadab Kabir
Simandeep Singh
IS Sohi
Tanvir Mehdi
CK Tshuma
R Walters
CM Willoughby
Zakir Hossain

# 6. *Comparative Analysis*

In [74]:
df.head(3)

,name,span,matches,innings,not_outs,runs,highest_score,average,balls_faced,strike_rate,century,half_century,ducks,country,start_year,end_year,decade,runs_per_innings,runs_per_matches
0,SR Tendulkar,1990-2012,462.0,451,41,18426,200,44.94,21366,86.23,49,96,19,IND,1990,2012,1990s,40.855876,39.883117
1,KC Sangakkara,2000-2015,404.0,380,41,14234,169,41.98,18048,78.86,25,93,15,SL,2000,2015,2000s,37.457895,35.232673
2,V Kohli,2008-2023,292.0,280,44,13848,183,58.67,14797,93.58,50,72,16,IND,2008,2023,2000s,49.457143,47.424658

In [75]:
#26. Compare the batting averages of the top 10 run-scorers.
sorted_df = df.sort_values(by='runs', ascending=False)

In [76]:
top_10_run_scorers = sorted_df.head(10)

In [77]:
top_10_batting_averages = top_10_run_scorers[['name', 'average']]

In [78]:
print("Batting averages of the top 10 run-scorers:")
print(top_10_batting_averages)

Batting averages of the top 10 run-scorers:
               name  average
0      SR Tendulkar    44.94
1     KC Sangakkara    41.98
2           V Kohli    58.67
3        RT Ponting    42.03
4     ST Jayasuriya    32.50
5  DPMD Jayawardene    33.37
6    Inzamam-ul-Haq    39.52
7         JH Kallis    44.36
8        SC Ganguly    41.02
9          R Dravid    39.16

In [79]:
#27. How do the top 5 highest individual scores compare to their respective batting averages?
top_5_highest_scorers = df.sort_values(by='highest_score', ascending=False).head(5)
top_5_batting_averages = top_5_highest_scorers[['name', 'average']]
print("Batting averages of the top 5 highest-scorers:")
print(top_5_batting_averages)

Batting averages of the top 5 highest-scorers:
           name  average
11    RG Sharma    49.12
36   MJ Guptill    41.73
25     V Sehwag    35.05
12     CH Gayle    37.83
202  P Nissanka    44.50

In [80]:
#28. Analyze the strike rates of players with more than 10,000 runs.
more_than_10000_runs=df[df['runs']>10000]

In [81]:
analyze_strike_rate=more_than_10000_runs[['name','strike_rate']].sort_values(by='strike_rate',ascending=False)

In [82]:
analyze_strike_rate

                name  strike_rate
2            V Kohli        93.58
11         RG Sharma        91.97
4      ST Jayasuriya        91.31
10          MS Dhoni        87.56
12          CH Gayle        87.19
0       SR Tendulkar        86.23
14        TM Dilshan        86.23
3         RT Ponting        80.39
13           BC Lara        79.51
5   DPMD Jayawardene        78.96
1      KC Sangakkara        78.86
6     Inzamam-ul-Haq        74.24
8         SC Ganguly        73.70
7          JH Kallis        72.89
9           R Dravid        71.23

In [83]:
print("Strike rate analysis of players with more than 10,000 runs:")
more_than_10000_runs['strike_rate'].describe()

Strike rate analysis of players with more than 10,000 runs:

count    15.000000
mean     82.256667
std       7.410450
min      71.230000
25%      76.550000
50%      80.390000
75%      87.375000
max      93.580000
Name: strike_rate, dtype: float64

In [84]:
#29.Compare the performance of players with more than 50 not outs.
more_than_50_not_outs=df[df['not_outs']>50]

In [85]:
comparison_metrics =more_than_50_not_outs[['name', 'runs', 'average', 'strike_rate', 'century','not_outs']]
print("Performance comparison of players with more than 50 not outs:")
print(comparison_metrics)

Performance comparison of players with more than 50 not outs:
               name   runs  average  strike_rate  century  not_outs
6    Inzamam-ul-Haq  11739    39.52        74.24       10        53
7         JH Kallis  11579    44.36        72.89       17        53
10         MS Dhoni  10773    50.57        87.56       10        84
43         MG Bevan   6912    53.58        74.16        6        67
55        JN Rhodes   5935    35.11        80.90        2        51
73      Mahmudullah   5386    35.66        76.92        4        51
75        DR Martyn   5346    40.80        77.73        5        51
83     Abdul Razzaq   5080    29.70        81.25        3        57
90       MV Boucher   4686    28.57        84.76        1        57
95        CZ Harris   4379    29.00        66.51        1        62
118      SM Pollock   3519    26.45        86.69        1        72
154       HH Streak   2943    28.29        73.42        0        55
198      DL Vettori   2253    17.33        82.98        0        57
219      WPUJC Vaas   2025    13.68        72.42        0        72
537   M Muralidaran    674     6.80        77.56        0        63

In [86]:
#30. Identify players who have scored centuries in more than 10% of their matches.
df['century_percentage'] = (df['century'] / df['matches']) * 100

In [87]:
players_with_high_century_percentage = df[df['century_percentage'] > 10]

In [88]:
high_century_players = players_with_high_century_percentage[['name', 'matches', 'century', 'century_percentage']]

In [89]:
print("Players who have scored centuries in more than 10% of their matches:")
print(high_century_players)

Players who have scored centuries in more than 10% of their matches:
                    name  matches  century  century_percentage
0           SR Tendulkar    462.0       49           10.606061
2                V Kohli    292.0       50           17.123288
11             RG Sharma    262.0       31           11.832061
17        AB de Villiers    228.0       25           10.964912
26               HM Amla    181.0       27           14.917127
42             DA Warner    161.0       22           13.664596
46              S Dhawan    167.0       17           10.179641
48             Q de Kock    155.0       21           13.548387
60            Babar Azam    117.0       19           16.239316
72              AJ Finch    146.0       17           11.643836
78               SD Hope    124.0       16           12.903226
100               JJ Roy    116.0       12           10.344828
107          JM Bairstow    107.0       11           10.280374
119         Fakhar Zaman     82.0       11           13.414634
140          Imam-ul-Haq     72.0        9           12.500000
145           CS MacLeod     88.0       10           11.363636
164          Salman Butt     78.0        8           10.256410
197         Shubman Gill     44.0        6           13.636364
202           P Nissanka     55.0        6           10.909091
253            HT Tector     45.0        5           11.111111
279          DJ Mitchell     39.0        6           15.384615
284     RN ten Doeschate     33.0        5           15.151515
290             T Bavuma     38.0        5           13.157895
298   Rahmanullah Gurbaz     40.0        6           15.000000
301             DJ Malan     30.0        6           20.000000
304       Ibrahim Zadran     33.0        5           15.151515
349            DP Conway     32.0        5           15.625000
423             JN Malan     23.0        3           13.043478
433         M van Lingen     32.0        4           12.500000
481           R Ravindra     25.0        3           12.000000
552           B McMullen     18.0        2           11.111111
627         MG Bracewell     19.0        2           10.526316
710              JP Bray     15.0        2           13.333333
718             IA Karim      9.0        2           22.222222
734             H Thaker     12.0        2           16.666667
781           J Liyanage      9.0        1           11.111111
810    KJJ van Noortwijk      9.0        1           11.111111
864           T de Zorzi      5.0        1           20.000000
912          JD Campbell      6.0        1           16.666667
918        JAD Lawrenson      5.0        1           20.000000
930             AM Tribe      5.0        1           20.000000
938             Abid Ali      6.0        1           16.666667
953         BR McDermott      5.0        1           20.000000
1066      JF Kloppenburg      6.0        1           16.666667
1067             MJ Lumb      3.0        1           33.333333

# 7. *Predictive Analytics*

In [91]:
"""31. Predict the number of runs a player might score based on the number of matches played and their average.
PredictedÂ Runs = MatchesÂ Played Ã— BattingÂ Average """
# Predict the number of runs based on the number of matches played and batting average
df['predicted_runs'] = df['matches'] * df['average']
predicted_runs_df = df[['name', 'matches', 'average', 'predicted_runs', 'runs']]
print("Predicted runs based on matches played and batting average:")
print(predicted_runs_df)

Predicted runs based on matches played and batting average:
               name  matches  average  predicted_runs   runs
0      SR Tendulkar    462.0    44.94        20762.28  18426
1     KC Sangakkara    404.0    41.98        16959.92  14234
2           V Kohli    292.0    58.67        17131.64  13848
3        RT Ponting    375.0    42.03        15761.25  13704
4     ST Jayasuriya    442.0    32.50        14365.00  13390
...             ...      ...      ...             ...    ...
2306   Tanvir Mehdi      1.0     0.00            0.00      0
2307      CK Tshuma      2.0     0.00            0.00      0
2308      R Walters      2.0     0.00            0.00      0
2309  CM Willoughby      3.0     0.00            0.00      0
2310  Zakir Hossain      1.0     0.00            0.00      0

[2311 rows x 5 columns]